sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
script:
  - hexo generate # generate static files
after_script:
  - git config user.name "Matthew Wang"
  - git config user.email "wangmaozhu@foxmail.com"
  - git remote add coding "https://${CODING_TOKEN}@e.coding.net/matthew-wang/matt-coding.git"
  - git push coding HEAD:source --force
  - cd ./public
  - git init
  - echo "blog.getatny.com" > CNAME
  - git add .
  - git commit -m "Update blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
env:
 global:
   - GH_REF: github.com/getatny/getatny.github.io.git
